filter:
    paths: [src/*]
    excluded_paths: [bin/*, tests/*, reports/*, vendor/*]
before_commands:
    - 'composer install --prefer-source'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [bin, reports, vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [bin, reports, vendor, tests]
